export interface PlanteArt {
  id: string
  norskNavn: string
  latinskNavn: string
  familie: string
  opprinnelse: string
  beskrivelse: string
  vanningIntervallDager: number
  lysforhold: 'lite' | 'middels' | 'mye'
  luftfuktighet: 'lav' | 'middels' | 'høy'
  vanskelighetsgrad: 'lett' | 'middels' | 'krevende'
  giftig: boolean
  giftigForDyr: boolean
  maksHøydeCm: number
  fakta: string[]
  stell: string[]
  tags: string[]
}

export const planteArtDatabase: PlanteArt[] = [
  {
    id: 'monstera-deliciosa',
    norskNavn: 'Vindusblad',
    latinskNavn: 'Monstera deliciosa',
    familie: 'Arumfamilien (Araceae)',
    opprinnelse: 'Mellom-Amerika',
    beskrivelse: 'En av de mest populære stueplantene med karakteristiske hullede blader. Vokser raskt og blir svært dekorativ.',
    vanningIntervallDager: 10,
    lysforhold: 'middels',
    luftfuktighet: 'middels',
    vanskelighetsgrad: 'lett',
    giftig: true,
    giftigForDyr: true,
    maksHøydeCm: 300,
    fakta: ['I naturen kan vindusblad bli over 20 meter høy.', 'Hullene i bladene er en evolusjonær tilpasning for å tåle kraftig tropisk regn.', 'Frukten er spiselig og smaker som en blanding av ananas og banan.', 'Plantens latinske navn betyr herlig monstre.'],
    stell: ['Vann når de øverste 3-4 cm av jorda er tørr.', 'Tørk bladene med fuktig klut månedlig.', 'Trives i indirekte lys - direkte sol brenner bladene.', 'Gjødsl annenhver uke i vekstsesongen.'],
    tags: ['populær', 'stor', 'luftrensende', 'tropisk', 'stueplante'],
  },
  {
    id: 'epipremnum-aureum',
    norskNavn: 'Gullranke',
    latinskNavn: 'Epipremnum aureum',
    familie: 'Arumfamilien (Araceae)',
    opprinnelse: 'Stillehavsøyene',
    beskrivelse: 'En nesten umulig å drepe klatreplante med hjerteformede gulgrønne blader. Perfekt for nybegynnere.',
    vanningIntervallDager: 10,
    lysforhold: 'lite',
    luftfuktighet: 'lav',
    vanskelighetsgrad: 'lett',
    giftig: true,
    giftigForDyr: true,
    maksHøydeCm: 200,
    fakta: ['Gullranke kan vokse i vann uten jord i lange perioder.', 'NASA har testet den som luftrenser i romstasjoner.', 'Er oppført på WHOs liste over luftrensende planter.', 'I naturen kan bladene bli over 60 cm store.'],
    stell: ['Tåler lite lys bedre enn nesten alle andre stueplanter.', 'Vann når jorda er tørr helt ned til bunnen av potten.', 'Klipp lange ranker for å stimulere tettere vekst.', 'Kan formeres enkelt ved å sette stiklinger i vann.'],
    tags: ['nybegynner', 'klatreplante', 'luftrensende', 'skyggetålende', 'stueplante'],
  },
  {
    id: 'sansevieria-trifasciata',
    norskNavn: 'Svigermors tunge',
    latinskNavn: 'Sansevieria trifasciata',
    familie: 'Aspargesfamilien (Asparagaceae)',
    opprinnelse: 'Vest-Afrika',
    beskrivelse: 'En ekstremt hardfør plante med stive sverdformede blader. En av de mest nøysomme stueplantene som finnes.',
    vanningIntervallDager: 21,
    lysforhold: 'lite',
    luftfuktighet: 'lav',
    vanskelighetsgrad: 'lett',
    giftig: true,
    giftigForDyr: true,
    maksHøydeCm: 120,
    fakta: ['En av få planter som produserer oksygen også om natten.', 'Tåler måneder uten vanning og klarer seg i nesten mørke rom.', 'Kalles også bajonettplante på grunn av de spisse bladspissene.', 'Har vært brukt til å lage tau og tekstilfibrer i Afrika.'],
    stell: ['Vann svært sparsomt - en gang i måneden om vinteren holder.', 'Den vanligste feilen er overvanning.', 'Trives i nesten alle lysforhold.', 'Pott om sjelden - den liker å stå tett i potten.'],
    tags: ['nybegynner', 'tørketålende', 'soverom', 'luftrensende', 'stueplante'],
  },
  {
    id: 'spathiphyllum',
    norskNavn: 'Fredskalle',
    latinskNavn: 'Spathiphyllum wallisii',
    familie: 'Arumfamilien (Araceae)',
    opprinnelse: 'Tropisk Amerika og Sørøst-Asia',
    beskrivelse: 'En elegant plante med blanke mørkegrønne blader og hvite blomster. Gir tydelig beskjed når den tørster.',
    vanningIntervallDager: 7,
    lysforhold: 'lite',
    luftfuktighet: 'høy',
    vanskelighetsgrad: 'lett',
    giftig: true,
    giftigForDyr: true,
    maksHøydeCm: 90,
    fakta: ['Fredskallen henger med hodet når den trenger vann og reiser seg raskt igjen.', 'En av de mest effektive luftrensende plantene ifølge NASA.', 'Blomstrer gjerne flere ganger i året dersom den trives.', 'Navnet fredskalle kommer fra den hvite fredsflagget-lignende blomsten.'],
    stell: ['Vann jevnlig - liker jevn jordfuktighet men ikke stående vann.', 'Tåler skygge bedre enn de fleste blomstrende planter.', 'Spray bladene med vann for å øke luftfuktigheten.', 'Fjern visne blomster for å stimulere til ny blomstring.'],
    tags: ['blomstrende', 'luftrensende', 'skyggetålende', 'populær', 'stueplante'],
  },
  {
    id: 'ficus-elastica',
    norskNavn: 'Gummifiken',
    latinskNavn: 'Ficus elastica',
    familie: 'Morbærfamilien (Moraceae)',
    opprinnelse: 'India og Malaysia',
    beskrivelse: 'En stilfull plante med store blanke mørkegrønne blader. Gir et arkitektonisk preg til rommet.',
    vanningIntervallDager: 10,
    lysforhold: 'middels',
    luftfuktighet: 'middels',
    vanskelighetsgrad: 'middels',
    giftig: true,
    giftigForDyr: true,
    maksHøydeCm: 200,
    fakta: ['Gummifiken ble historisk brukt til å produsere naturgummi.', 'Den hvite melkesaften kan irritere hud og slimhinner.', 'I India brukes røttene til å bygge levende broer.', 'Bladene kan bli opptil 30 cm lange.'],
    stell: ['Tørk bladene månedlig med fuktig klut.', 'Liker å stå lyst men uten direkte sol.', 'Misliker å bli flyttet.', 'Vann moderat - la de øverste 3 cm tørke mellom vanningene.'],
    tags: ['stilig', 'stor', 'arkitektonisk', 'populær', 'stueplante'],
  },
  {
    id: 'aloe-vera',
    norskNavn: 'Aloe vera',
    latinskNavn: 'Aloe vera',
    familie: 'Gresstreplantene (Asphodelaceae)',
    opprinnelse: 'Den arabiske halvøy',
    beskrivelse: 'En saftig og nyttig plante med tykke kjøttfulle blader fylt med gel. Har vært brukt medisinsk i over 6000 år.',
    vanningIntervallDager: 21,
    lysforhold: 'mye',
    luftfuktighet: 'lav',
    vanskelighetsgrad: 'lett',
    giftig: false,
    giftigForDyr: true,
    maksHøydeCm: 60,
    fakta: ['Aloe vera-gelen brukes mot solbrenthet og brannsår.', 'Egypterne kalte den udødelighetens plante for over 6000 år siden.', 'Planten er registrert i over 75000 skjønnhetsprodukter på verdensbasis.', 'Den kan overleve svært lenge uten vann.'],
    stell: ['Vann sjelden og grundig - la jorda tørke helt ut mellom vanningene.', 'Trenger mye lys - helst direkte sol noen timer daglig.', 'Bruk kaktus- eller sukkulentjord for best drenering.', 'Unngå å vanne på bladene.'],
    tags: ['sukkulente', 'nyttig', 'medisinsk', 'lettstelt', 'stueplante'],
  },
  {
    id: 'chlorophytum-comosum',
    norskNavn: 'Grønnrenner',
    latinskNavn: 'Chlorophytum comosum',
    familie: 'Aspargesfamilien (Asparagaceae)',
    opprinnelse: 'Sør-Afrika',
    beskrivelse: 'En hengende plante med lange smale blader og karakteristiske babyer som henger ned på lange stengler.',
    vanningIntervallDager: 7,
    lysforhold: 'middels',
    luftfuktighet: 'middels',
    vanskelighetsgrad: 'lett',
    giftig: false,
    giftigForDyr: false,
    maksHøydeCm: 60,
    fakta: ['Grønnrenner er en av de tryggeste plantene for hjem med barn og kjæledyr.', 'NASA fant at den fjerner 95% av giftige stoffer i luften på 24 timer.', 'Smaplantene kan enkelt plantes i ny jord.', 'Kan produsere hundrevis av avleggere i løpet av ett år.'],
    stell: ['Tåler de fleste lysforhold men trives best i indirekte lys.', 'Vann jevnlig men la de øverste 2 cm tørke mellom vanningene.', 'Klipp av brune bladspisser med saks.', 'Formeres enkelt ved å sette babyer i vann.'],
    tags: ['hengende', 'barnesikker', 'lettstelt', 'luftrensende', 'stueplante'],
  },
  {
    id: 'crassula-ovata',
    norskNavn: 'Pengetreet',
    latinskNavn: 'Crassula ovata',
    familie: 'Bergknappfamilien (Crassulaceae)',
    opprinnelse: 'Sør-Afrika og Mosambik',
    beskrivelse: 'Et kompakt trestammet tre med runde blanke blader. Regnes i mange kulturer som et lykkebringende symbol på velstand.',
    vanningIntervallDager: 14,
    lysforhold: 'mye',
    luftfuktighet: 'lav',
    vanskelighetsgrad: 'lett',
    giftig: false,
    giftigForDyr: true,
    maksHøydeCm: 90,
    fakta: ['I Kina og Japan regnes pengetreet som et symbol på lykke og velstand.', 'Kan bli over 100 år gammelt med godt stell.', 'Blomstrer med små stjernformede hvite eller rosa blomster om vinteren.', 'Bladene lagrer vann og fungerer som en naturlig reserve mot tørke.'],
    stell: ['Trives best i mye lys - gjerne noen timer direkte sol.', 'Vann moderat og la jorda tørke godt mellom vanningene.', 'Pott om kun når røttene fyller hele potten.', 'Gjødsl sparsomt - en gang i måneden i vekstsesongen.'],
    tags: ['sukkulente', 'lykke', 'lettstelt', 'tørketålende', 'stueplante'],
  },
  {
    id: 'zamioculcas-zamiifolia',
    norskNavn: 'ZZ-plante',
    latinskNavn: 'Zamioculcas zamiifolia',
    familie: 'Arumfamilien (Araceae)',
    opprinnelse: 'Øst-Afrika',
    beskrivelse: 'En svært hardfør plante med blanke mørkegrønne blader. Tåler forsømmelse bedre enn nesten noen annen stueplante.',
    vanningIntervallDager: 21,
    lysforhold: 'lite',
    luftfuktighet: 'lav',
    vanskelighetsgrad: 'lett',
    giftig: true,
    giftigForDyr: true,
    maksHøydeCm: 90,
    fakta: ['ZZ-planten lagrer vann i store røtter og tåler måneder uten vanning.', 'Den vokser svært sakte - bare noen centimeter per år.', 'Er nesten umulig å drepe av for lite lys eller glemte vanninger.', 'Ble ikke introdusert til Europa før på 1990-tallet.'],
    stell: ['Vann svært sjelden - en gang i måneden eller sjeldnere om vinteren.', 'Tåler nesten mørke rom.', 'Unngå overvanning for enhver pris.', 'Trenger ikke mye gjødsel - en gang i året er tilstrekkelig.'],
    tags: ['nybegynner', 'tørketålende', 'skyggetålende', 'kontor', 'stueplante'],
  },
  {
    id: 'dracaena-marginata',
    norskNavn: 'Draketre',
    latinskNavn: 'Dracaena marginata',
    familie: 'Aspargesfamilien (Asparagaceae)',
    opprinnelse: 'Madagaskar',
    beskrivelse: 'Et slankt elegant tre med lange smale blader med røde kanter. Gir en tropisk og arkitektonisk effekt.',
    vanningIntervallDager: 14,
    lysforhold: 'middels',
    luftfuktighet: 'middels',
    vanskelighetsgrad: 'lett',
    giftig: false,
    giftigForDyr: true,
    maksHøydeCm: 180,
    fakta: ['Draketre ble i gammel tid brukt til å lage en rød harpiks kalt drakblod.', 'Kan bli svært gammelt - noen eksemplarer er anslått til over 650 år.', 'Er en av de mest effektive plantene for å rense luften.', 'Navnet dracaena kommer fra det greske ordet for hunn-drage.'],
    stell: ['Vann moderat og la de øverste 3-4 cm tørke mellom vanningene.', 'Sensitiv for fluor i kranvann - bruk gjerne filtrert vann.', 'Trives best i lyst rom uten direkte sol.', 'Klipp av brune bladspisser for pent utseende.'],
    tags: ['stilig', 'stor', 'luftrensende', 'tropisk', 'stueplante'],
  },
  {
    id: 'phalaenopsis',
    norskNavn: 'Sommerfuglorkkidé',
    latinskNavn: 'Phalaenopsis spp.',
    familie: 'Orkidéfamilien (Orchidaceae)',
    opprinnelse: 'Sørøst-Asia og Australia',
    beskrivelse: 'Den mest populære orkidéen i Norge med elegante blomster som holder i måneder.',
    vanningIntervallDager: 10,
    lysforhold: 'middels',
    luftfuktighet: 'høy',
    vanskelighetsgrad: 'middels',
    giftig: false,
    giftigForDyr: false,
    maksHøydeCm: 60,
    fakta: ['Orkidéfamilien er en av verdens største plantefamilier med nesten 25000 arter.', 'Phalaenopsis er den mest solgte blomsterpotten i hele verden.', 'En velstelt orkidé kan blomstre i opptil 6 måneder.', 'Røttene er grønne når de er fuktige og sølvgrå når de er tørre.'],
    stell: ['Vann med ett eggeglass vann per uke - aldri mer.', 'La aldri røttene stå i stillestående vann.', 'Klipp stilken over et knutepunkt etter blomstring.', 'Trives i indirekte lys - aldri direkte sol.'],
    tags: ['blomstrende', 'elegant', 'populær', 'gave', 'stueplante'],
  },
  {
    id: 'hoya-carnosa',
    norskNavn: 'Voksblomst',
    latinskNavn: 'Hoya carnosa',
    familie: 'Hundegrassfamilien (Apocynaceae)',
    opprinnelse: 'Øst-Asia og Australia',
    beskrivelse: 'En kjærkommen klatreplante med tykke blanke blader og vakre duftende blomsterklynger. Kan leve i generasjoner.',
    vanningIntervallDager: 14,
    lysforhold: 'middels',
    luftfuktighet: 'middels',
    vanskelighetsgrad: 'lett',
    giftig: false,
    giftigForDyr: false,
    maksHøydeCm: 200,
    fakta: ['Voksblomst kan leve i over 30 år og bli et familiearvstykke.', 'Blomstene produserer store mengder søt nektar og dufter sterkest om natten.', 'Aldri klipp av de tomme blomsterstilkene - de blomstrer igjen fra samme sted.', 'Kalles porselensblomst fordi blomstene ser ut som de er laget av porselen.'],
    stell: ['Liker å stå tett i potten - pott om sjelden.', 'Vann moderat og la jorda nesten tørke mellom vanningene.', 'Klipp aldri av gamle blomsterstilker.', 'Trives i lyst rom med indirekte lys.'],
    tags: ['blomstrende', 'klatreplante', 'duftende', 'lettstelt', 'stueplante'],
  },
  {
    id: 'ficus-lyrata',
    norskNavn: 'Felefikentre',
    latinskNavn: 'Ficus lyrata',
    familie: 'Morbærfamilien (Moraceae)',
    opprinnelse: 'Vest- og Sentral-Afrika',
    beskrivelse: 'Et trendy og arkitektonisk tre med store bølgete blader. En favoritt i moderne nordisk interiør.',
    vanningIntervallDager: 10,
    lysforhold: 'mye',
    luftfuktighet: 'middels',
    vanskelighetsgrad: 'krevende',
    giftig: true,
    giftigForDyr: true,
    maksHøydeCm: 200,
    fakta: ['Felefikentreeet er kåret til en av de mest trendende stueplantene det siste tiåret.', 'I naturen er det en epifytt som vokser på andre trær i regnskogen.', 'Bladene kan bli opptil 45 cm lange og 30 cm brede.', 'Misliker å bli flyttet - mister gjerne blader ved plassskifte.'],
    stell: ['Finn den perfekte plassen og la den stå.', 'Trenger mye lys men ikke direkte brennende sol.', 'Vann når de øverste 3 cm av jorda er tørr.', 'Tørk de store bladene månedlig.'],
    tags: ['trendy', 'arkitektonisk', 'stor', 'nordisk interiør', 'stueplante'],
  },
  {
    id: 'alocasia-amazonica',
    norskNavn: 'Elefantøre',
    latinskNavn: 'Alocasia amazonica',
    familie: 'Arumfamilien (Araceae)',
    opprinnelse: 'Sørøst-Asia',
    beskrivelse: 'En dramatisk plante med store mørke blader med kontrasterende hvite bladnerver. Imponerende og krevende.',
    vanningIntervallDager: 7,
    lysforhold: 'middels',
    luftfuktighet: 'høy',
    vanskelighetsgrad: 'krevende',
    giftig: true,
    giftigForDyr: true,
    maksHøydeCm: 90,
    fakta: ['Til tross for navnet amazonica er den ikke fra Amazonas men en hybrid fra Asia.', 'Bladene kan bli opp til 50 cm lange.', 'Planten kan gå i dvale om vinteren og miste alle blader.', 'Liker å svette - det er normalt at det drypper vann fra bladspissene.'],
    stell: ['Trenger høy luftfuktighet - spray daglig eller bruk luftfukter.', 'Vann jevnlig men la de øverste 3 cm tørke mellom vanningene.', 'Hold unna trekk og kalde vinduer.', 'Om planten går i dvale - ikke kast den bare vann sparsomt og vent.'],
    tags: ['dramatisk', 'krevende', 'tropisk', 'eksotisk', 'stueplante'],
  },
  {
    id: 'tradescantia-zebrina',
    norskNavn: 'Sebrastjernemure',
    latinskNavn: 'Tradescantia zebrina',
    familie: 'Spiderwortfamilien (Commelinaceae)',
    opprinnelse: 'Mexico og Mellom-Amerika',
    beskrivelse: 'En raskvoksende hengende plante med stripete lilla og sølvgrønne blader. Enkel å stelle og formere.',
    vanningIntervallDager: 7,
    lysforhold: 'middels',
    luftfuktighet: 'middels',
    vanskelighetsgrad: 'lett',
    giftig: false,
    giftigForDyr: true,
    maksHøydeCm: 30,
    fakta: ['Sebrastjernemure vokser så raskt at den kan bli en stor plante i løpet av én sommer.', 'Jo mer lys den får jo mer intens blir den lilla fargen.', 'Stiklinger slår rot i vann på bare noen dager.', 'Er nær beslektet med Moses-i-kurven.'],
    stell: ['Klyp av skuddspissene jevnlig for tett og frodig vekst.', 'Vann jevnlig - liker jevn jordfuktighet.', 'Trives best i lyst rom.', 'Formeres ekstremt enkelt - bare sett en stikkling i vann.'],
    tags: ['hengende', 'fargerik', 'lettstelt', 'rask vekst', 'stueplante'],
  },
  {
    id: 'rosa-spp',
    norskNavn: 'Rose',
    latinskNavn: 'Rosa spp.',
    familie: 'Rosefamilien (Rosaceae)',
    opprinnelse: 'Asia, Europa og Nord-Amerika',
    beskrivelse: 'Norges mest elskede hageplante med duftende blomster i utallige farger. Finnes i varianter tilpasset norsk klima.',
    vanningIntervallDager: 5,
    lysforhold: 'mye',
    luftfuktighet: 'middels',
    vanskelighetsgrad: 'middels',
    giftig: false,
    giftigForDyr: false,
    maksHøydeCm: 200,
    fakta: ['Rosen er verdens mest dyrkede prydplante og dyrkes i over 80 land.', 'Det finnes over 30000 registrerte rosenkultivar på verdensbasis.', 'Nypene fra rose er svært rike på C-vitamin - mer enn sitrus.', 'Norsk roseavl har produsert sorter spesielt tilpasset kaldt klima.'],
    stell: ['Beskjær om våren når frostfaren er over, vanligvis i april i Sør-Norge.', 'Vann ved rotsonen ikke på bladene for å unngå soppsjukdommer.', 'Gjødsl regelmessig med rosegjødsel fra mai til august.', 'Dekk til om høsten med bark eller never for å beskytte røttene mot frost.'],
    tags: ['hageplante', 'blomstrende', 'duftende', 'norsk klassiker'],
  },
  {
    id: 'solanum-lycopersicum',
    norskNavn: 'Tomat',
    latinskNavn: 'Solanum lycopersicum',
    familie: 'Søtvierfamilien (Solanaceae)',
    opprinnelse: 'Vest-Sør-Amerika',
    beskrivelse: 'En av de mest populære grønnsakhageplantene i Norge. Trives godt i drivhus eller varm skjermet sørvendt plass.',
    vanningIntervallDager: 2,
    lysforhold: 'mye',
    luftfuktighet: 'middels',
    vanskelighetsgrad: 'middels',
    giftig: false,
    giftigForDyr: false,
    maksHøydeCm: 180,
    fakta: ['Tomaten er botanisk sett en frukt men brukes som grønnsak i matlaging.', 'Det finnes over 10000 tomatsorter på verdensbasis.', 'Bladene og stilkene på tomaten er giftige - kun frukten er spiselig.', 'Tomaten kom til Europa fra Amerika på 1500-tallet.'],
    stell: ['Vann jevnlig og regelmessig - ujevn vanning gir sprekker i frukten.', 'Klyp av sideskudd mellom hovedstamme og grener.', 'Støtt opp planten med staker etter hvert som den vokser.', 'Gjødsl med tomatgjødsel annenhver uke fra blomstring starter.'],
    tags: ['nyttevekst', 'grønnsak', 'drivhus', 'spiselig'],
  },
  {
    id: 'lactuca-sativa',
    norskNavn: 'Salat',
    latinskNavn: 'Lactuca sativa',
    familie: 'Korgplantefamilien (Asteraceae)',
    opprinnelse: 'Middelhavsområdet og Vest-Asia',
    beskrivelse: 'En rask og enkel nyttevekst som egner seg godt i norske hager og på balkonger. Kan høstes allerede etter 4-6 uker.',
    vanningIntervallDager: 2,
    lysforhold: 'middels',
    luftfuktighet: 'middels',
    vanskelighetsgrad: 'lett',
    giftig: false,
    giftigForDyr: false,
    maksHøydeCm: 40,
    fakta: ['Salat er en av de eldste dyrkede grønnsakene - spist av egypterne for 4500 år siden.', 'Plukksalat kan høstes blad for blad slik at planten fortsetter å vokse.', 'Salat er 95% vann.', 'Tåler lett frost og kan dyrkes tidlig vår og sen høst i Norge.'],
    stell: ['Så direkte i bed fra mai eller innendørs fra mars.', 'Vann jevnlig - salat liker fuktig jord og tørker raskt ut.', 'Høst om morgenen for best smak og lengst holdbarhet.', 'Unngå å så om sommeren - salat skyter raskt i varmen.'],
    tags: ['nyttevekst', 'grønnsak', 'rask', 'balkong'],
  },
  {
    id: 'fragaria-x-ananassa',
    norskNavn: 'Jordbær',
    latinskNavn: 'Fragaria x ananassa',
    familie: 'Rosefamilien (Rosaceae)',
    opprinnelse: 'Europa (krysning av amerikanske arter)',
    beskrivelse: 'En norsk sommerfavoritt som trives godt i hele landet. Gir rikelig avling og passer utmerket i bed krukker og kasser.',
    vanningIntervallDager: 3,
    lysforhold: 'mye',
    luftfuktighet: 'middels',
    vanskelighetsgrad: 'lett',
    giftig: false,
    giftigForDyr: false,
    maksHøydeCm: 30,
    fakta: ['Norge er blant de landene i verden med høyest jordbærforbruk per innbygger.', 'Jordbær er egentlig ikke et bær botanisk sett - det er en samlingsfrukt.', 'Sorten Korona er den mest dyrkede jordbærsorten i Norge.', 'Jordbær formerer seg naturlig ved å sende ut løpere som slår rot.'],
    stell: ['Plant i solrik godt drenert jord med pH mellom 5,5 og 6,5.', 'Legg jordbærmatte eller halm under bærene for å holde dem rene.', 'Klipp av løpere gjennom sesongen.', 'Skift ut planter etter 3-4 år for best avling.'],
    tags: ['nyttevekst', 'frukt', 'norsk favoritt', 'balkong'],
  },
  {
    id: 'daucus-carota',
    norskNavn: 'Gulrot',
    latinskNavn: 'Daucus carota',
    familie: 'Skjermplantefamilien (Apiaceae)',
    opprinnelse: 'Afghanistan',
    beskrivelse: 'En av de mest dyrkede rotgrønnsakene i Norge. Trives i løs steinfattig jord og er relativt enkel å dyrke.',
    vanningIntervallDager: 4,
    lysforhold: 'mye',
    luftfuktighet: 'middels',
    vanskelighetsgrad: 'lett',
    giftig: false,
    giftigForDyr: false,
    maksHøydeCm: 50,
    fakta: ['Opprinnelig var vill gulrot hvit eller lilla - oransje gulrot ble avlet frem i Nederland på 1600-tallet.', 'Gulrot er rik på betakaroten som kroppen omdanner til vitamin A.', 'Jo søtere jord jo søtere gulrot - kulde og frost øker sukkerinnholdet.', 'Gulrottoppen er spiselig og kan brukes som krydderurt.'],
    stell: ['Så direkte i bed fra april - gulrot liker ikke å flyttes.', 'Løs jorda godt ned til 30 cm dybde for lange rette røtter.', 'Tynn ut til 5-8 cm mellom plantene etter spiring.', 'Høst fra august - la gjerne noen stå til etter første frost for søtere smak.'],
    tags: ['nyttevekst', 'rotgrønnsak', 'norsk klassiker', 'bed'],
  },
  {
    id: 'allium-schoenoprasum',
    norskNavn: 'Gressløk',
    latinskNavn: 'Allium schoenoprasum',
    familie: 'Amaryllisfamilien (Amaryllidaceae)',
    opprinnelse: 'Europa, Asia og Nord-Amerika',
    beskrivelse: 'En flerårig urt som vokser naturlig i norsk natur. Perfekt på kjøkkenbenken eller i blomsterbedet og svært hardfør.',
    vanningIntervallDager: 5,
    lysforhold: 'mye',
    luftfuktighet: 'middels',
    vanskelighetsgrad: 'lett',
    giftig: false,
    giftigForDyr: false,
    maksHøydeCm: 40,
    fakta: ['Gressløk er en av de eldste kjente krydderurtene og brukes i over 2000 år.', 'Den er en av få urter som vokser vilt i norsk natur.', 'Blomstene er spiselige og kan brukes til pynt i salater.', 'Tåler norsk vinter uten beskyttelse og kommer tilbake hvert år.'],
    stell: ['Del opp tuer hvert 3-4 år for å holde planten frisk og frodig.', 'Klipp ned til 5 cm høyde etter høsting for ny vekst.', 'Fjern blomsterstilker for å forlenge høstesesongen.', 'Trives i de fleste jordblandinger.'],
    tags: ['urt', 'nyttevekst', 'flerårig', 'norsk natur'],
  },
  {
    id: 'ocimum-basilicum',
    norskNavn: 'Basilikum',
    latinskNavn: 'Ocimum basilicum',
    familie: 'Leppeblomstfamilien (Lamiaceae)',
    opprinnelse: 'Tropisk Asia',
    beskrivelse: 'Den mest populære krydderurten i Norge. Elsker varme og sol og passer godt på solfylt kjøkkenvinduskarm.',
    vanningIntervallDager: 3,
    lysforhold: 'mye',
    luftfuktighet: 'middels',
    vanskelighetsgrad: 'middels',
    giftig: false,
    giftigForDyr: false,
    maksHøydeCm: 50,
    fakta: ['Basilikum er en av verdens mest brukte krydderurter og brukes i over 150 land.', 'Det finnes over 60 sorter basilikum fra søt til sitron og thai.', 'I antikkens Hellas ble basilikum sett på som et tegn på sorg og død.', 'Basilikum tåler ikke frost - selv 5 grader kan skade planten.'],
    stell: ['Klyp av blomsterstilker for å forlenge bladproduksjonen.', 'Vann ved rotsonen ikke på bladene.', 'Trives best innendørs om sommeren eller i drivhus i Norge.', 'Ta stiklinger på slutten av sommeren for å ha basilikum gjennom vinteren.'],
    tags: ['urt', 'krydder', 'kjøkken', 'ettårig'],
  },
  {
    id: 'lavandula-angustifolia',
    norskNavn: 'Lavendel',
    latinskNavn: 'Lavandula angustifolia',
    familie: 'Leppeblomstfamilien (Lamiaceae)',
    opprinnelse: 'Middelhavsområdet',
    beskrivelse: 'En duftende og vakker prydplante som overraskende godt tåler norske vintre på solrike og godt drenerte steder.',
    vanningIntervallDager: 10,
    lysforhold: 'mye',
    luftfuktighet: 'lav',
    vanskelighetsgrad: 'middels',
    giftig: false,
    giftigForDyr: false,
    maksHøydeCm: 80,
    fakta: ['Lavendel har vært brukt som medisinplante og parfyme i over 2500 år.', 'Duften fra lavendel har vist seg å ha beroligende effekt i flere studier.', 'Blomstene tiltrekker seg bier og humler.', 'Tørkede lavendelblomster brukes som naturlig møllmiddel.'],
    stell: ['Plant i svært godt drenert jord - lavendel hater å stå vått.', 'Beskjær ned til vedaktig stamme etter blomstring.', 'Trenger ikke gjødsling.', 'Dekk til om vinteren i kalde strøk av Norge.'],
    tags: ['hageplante', 'duftende', 'blomstrende', 'humlevennlig'],
  },
  {
    id: 'helianthus-annuus',
    norskNavn: 'Solsikke',
    latinskNavn: 'Helianthus annuus',
    familie: 'Korgplantefamilien (Asteraceae)',
    opprinnelse: 'Nord-Amerika',
    beskrivelse: 'En rask og givende ettårig plante med store gule blomster. Populær i norske hager og blant barn.',
    vanningIntervallDager: 4,
    lysforhold: 'mye',
    luftfuktighet: 'middels',
    vanskelighetsgrad: 'lett',
    giftig: false,
    giftigForDyr: false,
    maksHøydeCm: 300,
    fakta: ['Unge solsikker følger solen gjennom dagen - et fenomen kalt heliotropisme.', 'Et solsikkehode er egentlig opptil 2000 små blomster samlet.', 'Solsikkefrø er rike på E-vitamin magnesium og sunt fett.', 'Den høyeste registrerte solsikken målte over 9 meter.'],
    stell: ['Så direkte på friland etter siste frost vanligvis i mai i Sør-Norge.', 'Vann jevnlig men tåler kortere tørkeperioder godt.', 'Støtt opp høye sorter med staker i vindfulle strøk.', 'La hoder stå til høst - fugler elsker frøene.'],
    tags: ['hageplante', 'ettårig', 'blomstrende', 'fuglmat'],
  },
  {
    id: 'pisum-sativum',
    norskNavn: 'Erter',
    latinskNavn: 'Pisum sativum',
    familie: 'Erteblomstfamilien (Fabaceae)',
    opprinnelse: 'Middelhavsområdet og Sørvest-Asia',
    beskrivelse: 'En enkel og populær nyttevekst som trives godt i norsk klima. Klatrende sorter passer fint langs gjerder.',
    vanningIntervallDager: 4,
    lysforhold: 'mye',
    luftfuktighet: 'middels',
    vanskelighetsgrad: 'lett',
    giftig: false,
    giftigForDyr: false,
    maksHøydeCm: 150,
    fakta: ['Erter var den planten Gregor Mendel brukte til å oppdage arvelærens lover.', 'Erter binder nitrogen fra luften og forbedrer jordens næringsinnhold.', 'Frosne erter er ofte mer næringsrike enn ferske.', 'Det finnes over 1000 registrerte ertesorter på verdensbasis.'],
    stell: ['Så tidlig - erter tåler lett frost og kan sås fra april i Sør-Norge.', 'Sett opp netting eller pinner for klatrende sorter.', 'Vann jevnlig under blomstring og belgsetting.', 'Høst jevnlig for kontinuerlig produksjon gjennom sesongen.'],
    tags: ['nyttevekst', 'grønnsak', 'klatreplante', 'tidligsås'],
  },
  {
    id: 'mentha-spicata',
    norskNavn: 'Grønmynte',
    latinskNavn: 'Mentha spicata',
    familie: 'Leppeblomstfamilien (Lamiaceae)',
    opprinnelse: 'Europa og sørvest-Asia',
    beskrivelse: 'En duftende og rask flerårig urt. Plantes best i krukke da den sprer seg aggressivt i bed.',
    vanningIntervallDager: 4,
    lysforhold: 'middels',
    luftfuktighet: 'middels',
    vanskelighetsgrad: 'lett',
    giftig: false,
    giftigForDyr: false,
    maksHøydeCm: 60,
    fakta: ['Mynte vokser vilt langs bekker og fuktige steder i norsk natur.', 'Det finnes over 600 myntesorter og hybrider på verdensbasis.', 'Mynte holder skadedyr borte - planter den gjerne ved kål og gulrot.', 'Tåler norsk vinter og kommer tilbake hvert år.'],
    stell: ['Plant alltid i krukke for å hindre spredning i bedet.', 'Klyp av blomsterstilker for å forlenge bladproduksjonen.', 'Del opp tuer hvert 2-3 år.', 'Høst jevnlig - jo mer du klipper jo tettere vokser den.'],
    tags: ['urt', 'krydder', 'flerårig', 'duftende'],
  },
  {
    id: 'thymus-vulgaris',
    norskNavn: 'Timian',
    latinskNavn: 'Thymus vulgaris',
    familie: 'Leppeblomstfamilien (Lamiaceae)',
    opprinnelse: 'Middelhavsområdet',
    beskrivelse: 'En liten aromatisk og hardfør flerårig urt. Perfekt i steinhager langs kantstein og i krukker på solrike plasser.',
    vanningIntervallDager: 7,
    lysforhold: 'mye',
    luftfuktighet: 'lav',
    vanskelighetsgrad: 'lett',
    giftig: false,
    giftigForDyr: false,
    maksHøydeCm: 30,
    fakta: ['Timian ble brukt av egypterne til balsamering for over 3000 år siden.', 'Det aktive stoffet tymol i timian har dokumenterte antibakterielle egenskaper.', 'Timian tiltrekker seg bier og er en viktig pollinatorplante.', 'Tåler norsk vinter godt og er en av de hardeste middelhavskrydderurtene.'],
    stell: ['Plantes i godt drenert jord - hater å stå vått.', 'Beskjær lett etter blomstring for tett og kompakt vekst.', 'Trenger minimal gjødsling.', 'Høst jevnlig gjennom sommeren - frisk timian er langt mer aromatisk enn tørket.'],
    tags: ['urt', 'krydder', 'flerårig', 'tørketålende'],
  },
  {
    id: 'tulipa-spp',
    norskNavn: 'Tulipan',
    latinskNavn: 'Tulipa spp.',
    familie: 'Liljefamilien (Liliaceae)',
    opprinnelse: 'Sentral-Asia og Tyrkia',
    beskrivelse: 'Et norsk vårsymbol som plantes om høsten og blomstrer fra april til mai. Finnes i hundrevis av farger og former.',
    vanningIntervallDager: 7,
    lysforhold: 'mye',
    luftfuktighet: 'middels',
    vanskelighetsgrad: 'lett',
    giftig: true,
    giftigForDyr: true,
    maksHøydeCm: 70,
    fakta: ['Tulipanmanien på 1600-tallet i Nederland var en av historiens første spekulasjonsbobler.', 'På høyden av tulipanmanien kostet en enkelt løk mer enn et hus i Amsterdam.', 'Tulipanblomsten er spiselig og brukes i salater i Tyrkia og Iran.', 'Det finnes over 3000 registrerte tulipansorter.'],
    stell: ['Plant løkene i oktober-november 10-15 cm dype og 10 cm fra hverandre.', 'La bladene visne naturlig etter blomstring.', 'Ta opp løkene etter blomstring og oppbevar tørt til høstplanting.', 'Planter godt i gruster og sandjord - hater stillestående vann.'],
    tags: ['hageplante', 'blomstrende', 'løkplante', 'vår'],
  },
  {
    id: 'narcissus-spp',
    norskNavn: 'Påskelilje',
    latinskNavn: 'Narcissus spp.',
    familie: 'Amaryllisfamilien (Amaryllidaceae)',
    opprinnelse: 'Europa og Nord-Afrika',
    beskrivelse: 'Et av de første tegnene på norsk vår. Hardfør løkplante som sprer seg og blomstrer trofast år etter år.',
    vanningIntervallDager: 10,
    lysforhold: 'mye',
    luftfuktighet: 'middels',
    vanskelighetsgrad: 'lett',
    giftig: true,
    giftigForDyr: true,
    maksHøydeCm: 50,
    fakta: ['Påskelilje inneholder giftige alkaloider som holder bort gnagere.', 'Den blomstrer trofast i samme bed i tiår uten å bli tatt opp.', 'Blomstene er allergifremkallende for noen - bruk hansker ved håndtering.', 'Wales har påskelilja som nasjonalblomst.'],
    stell: ['Plant løkene i september-oktober 10 cm dype.', 'La bladene stå til de er helt gule etter blomstring.', 'Trenger sjelden vanning - tåler norsk vinter godt.', 'Del opp store tuer hvert 5-6 år for best blomstring.'],
    tags: ['hageplante', 'blomstrende', 'løkplante', 'vår'],
  },
  {
    id: 'rhododendron-spp',
    norskNavn: 'Rododendron',
    latinskNavn: 'Rhododendron spp.',
    familie: 'Lyngfamilien (Ericaceae)',
    opprinnelse: 'Asia, Europa og Nord-Amerika',
    beskrivelse: 'En av Norges mest populære hageplanter med spektakulær blomstring. Trives best i sur humusrik jord i halvskygge.',
    vanningIntervallDager: 7,
    lysforhold: 'middels',
    luftfuktighet: 'høy',
    vanskelighetsgrad: 'middels',
    giftig: true,
    giftigForDyr: true,
    maksHøydeCm: 400,
    fakta: ['Rododendron er giftig i alle deler - inkludert nektar og honning fra blomstene.', 'Det finnes over 1000 rododendronarter og tusenvis av kultivar.', 'Er nær beslektet med norsk røsslyng og krekling.', 'Nordens største rododendronsamling finnes på Milde utenfor Bergen.'],
    stell: ['Plant i sur jord med pH mellom 4,5 og 5,5.', 'Vann med regnvann om mulig.', 'Mulch med barkflis rundt planten.', 'Fjern vissent blomsterhode etter blomstring.'],
    tags: ['hageplante', 'blomstrende', 'busk', 'norsk favoritt'],
  },
  {
    id: 'ribes-nigrum',
    norskNavn: 'Solbær',
    latinskNavn: 'Ribes nigrum',
    familie: 'Stikkelsbærfamilien (Grossulariaceae)',
    opprinnelse: 'Nord-Europa og Nord-Asia',
    beskrivelse: 'En hardfør bærbusk som trives utmerket i hele Norge. Gir rikelige avlinger av næringsrike mørke bær.',
    vanningIntervallDager: 7,
    lysforhold: 'mye',
    luftfuktighet: 'middels',
    vanskelighetsgrad: 'lett',
    giftig: false,
    giftigForDyr: false,
    maksHøydeCm: 180,
    fakta: ['Solbær inneholder fire ganger mer C-vitamin enn appelsin.', 'Solbærjuice var en viktig C-vitaminkilde for norske barn under andre verdenskrig.', 'Bladene fra solbær kan brukes til te.', 'Tåler ned til minus 30 grader og vokser naturlig i norsk natur.'],
    stell: ['Plant i solrik til halvskygge plass med næringsrik jord.', 'Beskjær ut gammelt tre hvert år for å fornye busken.', 'Gjødsl med bærgjødsel tidlig om våren.', 'Dekk med nett mot fugler når bærene modner.'],
    tags: ['nyttevekst', 'bær', 'norsk natur', 'hardfør'],
  },
  {
    id: 'pelargonium-spp',
    norskNavn: 'Pelargonium',
    latinskNavn: 'Pelargonium spp.',
    familie: 'Storkenebb-familien (Geraniaceae)',
    opprinnelse: 'Sør-Afrika',
    beskrivelse: 'En av de mest populære balkong- og vindusboksplantene i Norge. Blomstrer rikt gjennom hele sommeren i varme farger.',
    vanningIntervallDager: 4,
    lysforhold: 'mye',
    luftfuktighet: 'lav',
    vanskelighetsgrad: 'lett',
    giftig: false,
    giftigForDyr: false,
    maksHøydeCm: 60,
    fakta: ['Pelargonium er ikke det samme som geranium selv om de ofte forveksles.', 'Det finnes over 200 ville pelargoniumarter i Sør-Afrika.', 'Duften fra pelargoniumblader holder mygg og andre insekter borte.', 'Kan overvintre innendørs og settes ut igjen neste sommer.'],
    stell: ['Vann jevnlig men la jorda tørke litt mellom vanningene.', 'Fjern vissne blomster for kontinuerlig ny blomstring.', 'Gjødsl annenhver uke med blomstergjødsel i vekstsesongen.', 'Ta inn om høsten og overvint kjølig og lyst innendørs.'],
    tags: ['balkongplante', 'blomstrende', 'sommer', 'fargerik'],
  },
  {
    id: 'spinacia-oleracea',
    norskNavn: 'Spinat',
    latinskNavn: 'Spinacia oleracea',
    familie: 'Meldestokfamilien (Amaranthaceae)',
    opprinnelse: 'Persia (Iran)',
    beskrivelse: 'En rask og næringsrik bladgrønnsak som trives godt i norsk klima. Tåler frost og gir avling tidlig og sent på sesongen.',
    vanningIntervallDager: 3,
    lysforhold: 'middels',
    luftfuktighet: 'middels',
    vanskelighetsgrad: 'lett',
    giftig: false,
    giftigForDyr: false,
    maksHøydeCm: 30,
    fakta: ['Spinat er rik på jern men myten om ekstremt høyt jerninnhold skyldes en regnefeil fra 1800-tallet.', 'Spinat skyter raskt til frø i varmen - dyrk tidlig vår og høst for best resultat.', 'Baby-spinat kan høstes allerede 3-4 uker etter såing.', 'Koking reduserer volumet med 90%.'],
    stell: ['Så tidlig - fra mars under fiberduk eller fra april ute.', 'Vann jevnlig og hold jorda fuktig.', 'Høst ytterblader jevnlig for kontinuerlig produksjon.', 'Unngå å så i juni-august - spinat skyter raskt til frø i varmen.'],
    tags: ['nyttevekst', 'bladgrønnsak', 'tidligsås', 'rask'],
  },
  {
    id: 'allium-cepa',
    norskNavn: 'Løk',
    latinskNavn: 'Allium cepa',
    familie: 'Amaryllisfamilien (Amaryllidaceae)',
    opprinnelse: 'Sentral-Asia',
    beskrivelse: 'En av verdens viktigste matplanter og en kjøkkenhageklassiker. Plantes som settløk tidlig om våren i norske hager.',
    vanningIntervallDager: 5,
    lysforhold: 'mye',
    luftfuktighet: 'middels',
    vanskelighetsgrad: 'lett',
    giftig: false,
    giftigForDyr: true,
    maksHøydeCm: 60,
    fakta: ['Løk har vært dyrket som mat i over 5000 år.', 'Det er tiosulfinater i løk som får øynene til å renne ved kutting.', 'Løk er giftig for hunder og katter selv i små mengder.', 'Avlingene i Norge er mellom 80000 og 100000 tonn løk per år.'],
    stell: ['Plant settløk tidlig - fra april i Sør-Norge med spissen opp.', 'Ugras konkurrerer hardt med løk - hold bedet rent.', 'Høst når halvparten av toppene har falt - tørk godt før lagring.', 'Ikke vann de siste to ukene før høsting for bedre holdbarhet.'],
    tags: ['nyttevekst', 'grønnsak', 'norsk klassiker', 'bed'],
  },
  {
    id: 'beta-vulgaris',
    norskNavn: 'Rødbete',
    latinskNavn: 'Beta vulgaris',
    familie: 'Meldestokfamilien (Amaranthaceae)',
    opprinnelse: 'Middelhavskysten',
    beskrivelse: 'En fargerik og næringsrik rotgrønnsak som er enkel å dyrke i norske hager. Bladene er også spiselige.',
    vanningIntervallDager: 4,
    lysforhold: 'mye',
    luftfuktighet: 'middels',
    vanskelighetsgrad: 'lett',
    giftig: false,
    giftigForDyr: false,
    maksHøydeCm: 50,
    fakta: ['Rødbete var en av de viktigste matplantene i det gamle Roma.', 'Den karakteristiske røde fargen kommer fra pigmentet betanin.', 'Rødbetejuice har vist seg å senke blodtrykket i flere studier.', 'Bladene inneholder mer jern enn spinat.'],
    stell: ['Så direkte i bed fra mai - liker ikke å flyttes.', 'Tynn ut til 10 cm mellomrom etter spiring.', 'Høst når røttene er 5-8 cm i diameter for best smak.', 'Tåler lett frost og kan bli stående i jorda til november.'],
    tags: ['nyttevekst', 'rotgrønnsak', 'fargerik', 'bed'],
  },
  {
    id: 'cucumis-sativus',
    norskNavn: 'Agurk',
    latinskNavn: 'Cucumis sativus',
    familie: 'Gresskarfamilien (Cucurbitaceae)',
    opprinnelse: 'India',
    beskrivelse: 'En varmekjær grønnsak som trives godt i norsk drivhus eller varm skjermet sørvendt plass i hagen.',
    vanningIntervallDager: 2,
    lysforhold: 'mye',
    luftfuktighet: 'høy',
    vanskelighetsgrad: 'middels',
    giftig: false,
    giftigForDyr: false,
    maksHøydeCm: 200,
    fakta: ['Agurk er 96% vann og er en av de mest vannholdige grønnsakene.', 'Botanisk sett er agurk en frukt ikke en grønnsak.', 'Det finnes over 100 agurksorter fra mini til 60 cm lange varianter.', 'Agurk har vært dyrket i over 3000 år.'],
    stell: ['Start innendørs i april og plant ut i drivhus i mai.', 'Vann daglig i varmt vær.', 'Klyp av sideskudd over 2. blad for bedre fruktproduksjon.', 'Gjødsl annenhver uke med allsidig grønnsaksgjødsel.'],
    tags: ['nyttevekst', 'grønnsak', 'drivhus', 'varmekjær'],
  },
  {
    id: 'phaseolus-vulgaris',
    norskNavn: 'Bønner',
    latinskNavn: 'Phaseolus vulgaris',
    familie: 'Erteblomstfamilien (Fabaceae)',
    opprinnelse: 'Mellom-Amerika',
    beskrivelse: 'En varmekjær nyttevekst som gir god avling i norsk sommer. Klatrende sorter dekker raskt gjerder og espalier.',
    vanningIntervallDager: 3,
    lysforhold: 'mye',
    luftfuktighet: 'middels',
    vanskelighetsgrad: 'lett',
    giftig: false,
    giftigForDyr: false,
    maksHøydeCm: 200,
    fakta: ['Bønner binder nitrogen og gjør jorda rikere etter seg.', 'Rå bønner inneholder lektiner som kan gi mageproblemer - kok alltid godt.', 'Det finnes over 400 registrerte bønnesorter i Europa alene.', 'Bønner kom til Europa fra Amerika etter Kolumbus sin reise i 1492.'],
    stell: ['Så utendørs etter siste frost - bønner tåler ikke frost.', 'Sett opp staker eller netting for klatrende sorter.', 'Vann jevnlig under blomstring og belgsetting.', 'Høst jevnlig for å stimulere til kontinuerlig produksjon.'],
    tags: ['nyttevekst', 'grønnsak', 'klatreplante', 'nitrogenfiks'],
  },
]

export function søkPlanteArt(søkeord: string): PlanteArt[] {
  if (!søkeord || søkeord.length < 2) return []
  const lower = søkeord.toLowerCase()
  return planteArtDatabase.filter(p =>
    p.norskNavn.toLowerCase().includes(lower) ||
    p.latinskNavn.toLowerCase().includes(lower) ||
    p.familie.toLowerCase().includes(lower) ||
    p.tags.some(t => t.toLowerCase().includes(lower))
  ).slice(0, 8)
}
